<a href="https://colab.research.google.com/github/RomaViraj/APT/blob/master/Applied_Tech_Project_135_Solution_copy_v0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the lesson: 

**Collaborative Filtering I - Pearson Correlation**

---

#### Problem Statement

This is a transactional dataset that contains all the transactions occurring in the year 2011 for a UK-based and registered non-store online retail. 

As a data scientist, you need to analyse the data and recommend the top 20 gifts as per the average number of transactions as well as the top 20 gifts as per average ordered items, so that company can gain top brands that are being sold and increase its sales as per market demands.

---

### Dataset Description

The DataFrame consists of the following columns:

|Field|Description|
|---:|:---|
| InvoiceNo | Invoice number |
| StockCode | Product (item) code |
| Description | Product (item) name |
| Quantity | The quantities of each product (item) per transaction |
| InvoiceDate | Invoice Date and time |
| UnitPrice | Unit price |
| CustomerID | Unique ID of the customer|
| Country | Country name |

**Dataset source:** https://archive.ics.uci.edu/ml/datasets/online+retail#

**Citation:** Daqing Chen, Sai Liang Sain, and Kun Guo, Data mining for the online retail industry: A case study of RFM model-based customer segmentation using data mining, Journal of Database Marketing and Customer Strategy Management

Dua, D., & Graff, C.. (2017). UCI Machine Learning Repository.

**Dataset Link -** https://drive.google.com/uc?id=1BajrtGH5BF5WSmjgegymjDnA8NfhUH3y

---

### List of Activities
 
**Activity 1:** Import Modules and Read Data

**Activity 2:** Calculate Pearson Correlation Coefficient

**Activity 3:** Recommend Items Based on Similarity Score

---

#### Activity 1: Import Modules and Read Data

1. Import the necessary Python modules.

2. Read the data from the dummy variable to create a Pandas DataFrame and go through the necessary data-cleaning process (if required).

In [ ]:
# Import the required modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# Read the dataset and print first five records.
url = "https://drive.google.com/uc?id=1BajrtGH5BF5WSmjgegymjDnA8NfhUH3y"
df = pd.read_csv(url)

# Create a DataFrame with only required features.
df.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    539993     22386  ...    13313.0  United Kingdom
1    539993     21498  ...    13313.0  United Kingdom
2    539993     22379  ...    13313.0  United Kingdom
3    539993     20718  ...    13313.0  United Kingdom
4    539993    85099B  ...    13313.0  United Kingdom

[5 rows x 8 columns]

Get the information about the dataset.

In [ ]:
# Print the information of the DataFrame using the 'info()' function.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258913 entries, 0 to 258912
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    258913 non-null  object
 1   StockCode    258913 non-null  object
 2   Description  258913 non-null  object
 3   Quantity     258913 non-null  int64
 4   InvoiceDate  258913 non-null  object
 5   UnitPrice    258913 non-null  float64
 6   CustomerID   200920 non-null  float64
 7   Country      258913 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 15.8+ MB

Create a new DataFrame `ecommerce_df` that contains only the following features:
- `InvoiceNo`
- `Description`
- `Quantity`

In [ ]:
# Pull out 'InvoiceNo', 'Description', 'Quantity' columns
ecommerce_df = df[['InvoiceNo', 'Description', 'Quantity']]
ecommerce_df.head()

  InvoiceNo                Description  Quantity
0    539993    JUMBO BAG PINK POLKADOT        10
1    539993        RED RETROSPOT WRAP         25
2    539993   RECYCLING BAG RETROSPOT          5
3    539993  RED RETROSPOT SHOPPER BAG        10
4    539993    JUMBO BAG RED RETROSPOT        10

Get the information about the new dataset.

In [ ]:
# Print the information of the new DataFrame using the 'info()' function.
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258913 entries, 0 to 258912
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    258913 non-null  object
 1   Description  258913 non-null  object
 2   Quantity     258913 non-null  int64
dtypes: int64(1), object(2)
memory usage: 5.9+ MB

**Q:** Are there any missing values in the new DataFrame?

**A:** No.

**Q:** Are there any non-numeric columns? 

**A:** Yes.



---

#### Activity 2: Calculate Pearson Correlation Coefficient

1. Create a pivot table using `pivot_table()` function with parameters as `index = 'InvoiceNo'`, `columns=['Description']` and `values='Quantity'`.

2. Create a correlation matrix using the pivot table using the `corr()` function.

Create a pivot table using `pivot_table()`

In [ ]:
# Create a pivot table 
df_items = ecommerce_df.pivot_table(index='InvoiceNo', columns=['Description'], values='Quantity')
df_items.head(10)

Description   4 PURPLE FLOCK DINNER CANDLES  ...  water damaged
InvoiceNo                                    ...
539993                                  NaN  ...            NaN
540001                                  NaN  ...            NaN
540002                                  NaN  ...            NaN
540003                                  NaN  ...            NaN
540004                                  NaN  ...            NaN
540005                                  NaN  ...            NaN
540010                                  NaN  ...            NaN
540012                                  NaN  ...            NaN
540013                                  NaN  ...            NaN
540014                                  NaN  ...            NaN

[10 rows x 3684 columns]

Calculate correlation coefficients between features using the `corr()` function on the pivoted table.

**Note:** Below code cell will run for approx. 4-5 mins as there are many data values.

In [ ]:
# Calculate correlation coefficient between each pair of items
similarity_df = df_items.corr()
similarity_df

Description                      4 PURPLE FLOCK DINNER CANDLES  ...  water damaged
Description                                                     ...
 4 PURPLE FLOCK DINNER CANDLES                             1.0  ...            NaN
 50'S CHRISTMAS GIFT BAG LARGE                             NaN  ...            NaN
 DOLLY GIRL BEAKER                                         NaN  ...            NaN
 I LOVE LONDON MINI BACKPACK                               NaN  ...            NaN
 I LOVE LONDON MINI RUCKSACK                               NaN  ...            NaN
...                                                        ...  ...            ...
taig adjust                                                NaN  ...            NaN
temp adjustment                                            NaN  ...            NaN
test                                                       NaN  ...            NaN
water damage                                               NaN  ...            NaN
water damaged                                              NaN  ...            NaN

[3684 rows x 3684 columns]

**Q:** Is the `NaN` value here means there is no correlation?

**A:** No. As `NaN` shows that there is a missing value, which means that a particular item is not available in that `InvoiceNo`.

---

#### Activity 3: Recommend Items Based on similarity score 

1. Create a DataFrame by passing `JUMBO BAG PINK POLKADOT` to the above correlation DataFrame.

2. Sort the DataFrame and get the top 10 items that a customer might be likely to purchase if he purchases `JUMBO BAG PINK POLKADOT`.

Create a DataFrame containing the correlation coefficients of other items with `JUMBO BAG PINK POLKADOT` using the above correlation DataFrame.

In [ ]:
# Create a DataFrame containing the correlation coefficients of other items with `JUMBO BAG PINK POLKADOT`
similar_to_jumbo = similarity_df["JUMBO BAG PINK POLKADOT"]
similar_to_jumbo_df = pd.DataFrame(similar_to_jumbo)
similar_to_jumbo_df

                                JUMBO BAG PINK POLKADOT
Description
 4 PURPLE FLOCK DINNER CANDLES                      NaN
 50'S CHRISTMAS GIFT BAG LARGE                 0.399627
 DOLLY GIRL BEAKER                             0.717549
 I LOVE LONDON MINI BACKPACK                  -0.375907
 I LOVE LONDON MINI RUCKSACK                        NaN
...                                                 ...
taig adjust                                         NaN
temp adjustment                                     NaN
test                                                NaN
water damage                                        NaN
water damaged                                       NaN

[3684 rows x 1 columns]

Rename the column `JUMBO BAG PINK POLKADOT` with `correlation` in the above DataFrame.

In [ ]:
# Rename the column to 'correlation'.
similar_to_jumbo_df.rename(columns = {similar_to_jumbo_df.columns[0]: 'correlation'}, inplace = True)
similar_to_jumbo_df

                                correlation
Description
 4 PURPLE FLOCK DINNER CANDLES          NaN
 50'S CHRISTMAS GIFT BAG LARGE     0.399627
 DOLLY GIRL BEAKER                 0.717549
 I LOVE LONDON MINI BACKPACK      -0.375907
 I LOVE LONDON MINI RUCKSACK            NaN
...                                     ...
taig adjust                             NaN
temp adjustment                         NaN
test                                    NaN
water damage                            NaN
water damaged                           NaN

[3684 rows x 1 columns]

Sort the DataFrame using the `sort_values()` function in descending order to get the top 10 highly correlated items

In [ ]:
# Sort the DataFrame by 'correlation' column to find top 10 highly correlated items.
similar_to_jumbo_df.sort_values('correlation', ascending = False).head(10)

                                    correlation
Description
GREETING CARD, TWO SISTERS.                 1.0
TEA TIME TEA SET IN GIFT BOX                1.0
T-LIGHT HOLDER SILVER PETIT FOUR            1.0
BOOZE & WOMEN GREETING CARD                 1.0
FELT FARM ANIMAL RABBIT                     1.0
ASSORTED CIRCULAR MOBILE                    1.0
SET 6 CARDS SPARKLY REINDEER 17262          1.0
ASSORTED SHAPES PHOTO CLIP SILVER           1.0
ENAMEL PINK TEA CONTAINER                   1.0
EMBROIDERED RIBBON REEL RACHEL              1.0

**Q:** List down the top 5 items most correlated with `JUMBO BAG PINK POLKADOT`?

**A:** Top 5 most correlated items:
1. GREETING CARD, TWO SISTERS
2. TEA TIME TEA SET IN GIFT BOX
3. T-LIGHT HOLDER SILVER PETIT FOUR	
4. BOOZE & WOMEN GREETING CARD
5. FELT FARM ANIMAL RABBIT

---